/* Run this as root: $mysql -u root -p < DB_SUMM_CLEAR.sql */
-- USE STIR_CME_CL_SUMM;

-- DROP PROCEDURE IF EXISTS SelectAll;

-- DELIMITER $$
-- CREATE PROCEDURE SelectAll()
-- BEGIN
--   SHOW tables;
-- END$$

-- DELIMITER$$
-- CREATE PROCEDURE DropTable(table VARCHAR(32))
-- BEGIN
--   DROP TABLE IF EXISTS table;
-- END$$

DROP DATABASE IF EXISTS STIR_CME_C_SUMM;
DROP DATABASE IF EXISTS STIR_CME_W_SUMM;
DROP DATABASE IF EXISTS STIR_CME_S_SUMM;
DROP DATABASE IF EXISTS STIR_CME_SM_SUMM;
DROP DATABASE IF EXISTS STIR_CME_BO_SUMM;
DROP DATABASE IF EXISTS STIR_CME_FC_SUMM;
DROP DATABASE IF EXISTS STIR_CME_LC_SUMM;
DROP DATABASE IF EXISTS STIR_CME_CL_SUMM;
DROP DATABASE IF EXISTS STIR_CME_HO_SUMM;
DROP DATABASE IF EXISTS STIR_CME_NG_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_B_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_G_SUMM;
DROP DATABASE IF EXISTS STIR_CME_EH_SUMM;
DROP DATABASE IF EXISTS STIR_CME_RB_SUMM;
DROP DATABASE IF EXISTS STIR_CME_GC_SUMM;
DROP DATABASE IF EXISTS STIR_CME_HG_SUMM;
DROP DATABASE IF EXISTS STIR_CME_PA_SUMM;
DROP DATABASE IF EXISTS STIR_CME_PL_SUMM;
DROP DATABASE IF EXISTS STIR_CME_SI_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_CT_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_CC_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_KC_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_OJ_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_SB_SUMM;
DROP DATABASE IF EXISTS STIR_CME_RR_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_O_SUMM;
DROP DATABASE IF EXISTS STIR_ICE_CO_SUMM;

CREATE DATABASE IF NOT EXISTS STIR_CME_C_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_W_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_S_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_SM_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_BO_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_FC_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_LC_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_CL_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_HO_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_NG_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_B_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_G_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_EH_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_RB_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_GC_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_HG_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_PA_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_PL_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_SI_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_CT_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_CC_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_KC_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_OJ_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_SB_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_CME_RR_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_O_SUMM;
CREATE DATABASE IF NOT EXISTS STIR_ICE_CO_SUMM;
